In [1]:
!pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\nitu calla\appdata\roaming\python\python310\site-packages (4.11.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.14)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2022.12.7)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\nitu calla\appdata\roaming\python\python310\site-packages (from selenium) (0.10.3)
Requirement already satisfied: trio~=0.17 in c:\users\nitu calla\appdata\roaming\python\python310\site-packages (from selenium) (0.22.2)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: attrs>=20.1.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\nitu calla\appdata\roaming\python\python310\site-packages (from trio~=0.17->selenium) (1.1.3)
Requirement already satisfied: outcome in c:\users\nitu calla\appdata\roaming\python\python310\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\nitu calla\appdata\roaming\python\python310\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\nitu calla\appdata\roaming\python\python310\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
# Importing libraries
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import ElementNotInteractableException
from selenium.common.exceptions  import SessionNotCreatedException
from selenium.common.exceptions  import TimeoutException

import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import re
import pandas as pd
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains

Q1. 
Scrape the details of most viewed videos on YouTube from Wikipedia. Url = 
https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:

Rank, Name, Artist, Upload Date , Views

In [24]:
driver = webdriver.Chrome()

# Opening the flipkart.com pag Son the automated chome browser
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
time.sleep(2)
#maximize the window
driver.maximize_window()

In [25]:
Rank=[]
Name=[]
Artist=[]
Upload_date=[]
Views=[]

In [26]:
#scraping data
try:
    rank_ele=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[1]')
    for i in rank_ele[0:30]:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('NA')
except StaleElementReferenceException:
    Rank.append('NA')
    
# Extracting Name Via X path
try:
    name_ele=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[2]')
    for i in name_ele:
        Name.append(i.text)
except NoSuchElementExceptionhElementException:
    Name.append('NA')
except StaleElementReferenceException:
    Name.append('NA')
    
# Extracting Artist Name Via Xpath
try:
    artist_ele=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artist_ele:
        Artist.append(i.text)
except NoSuchElementExceptionhElementException:
    Artist.append('NA')
except StaleElementReferenceException:
    Artist.append('NA')

# Extracting Upload date Via Xpath
try:
    upload_date_ele=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in upload_date_ele:
        Upload_date.append(i.text)
except NoSuchElementExceptionhElementException:
    Upload_date.append('NA')
except StaleElementReferenceException:
    Upload_date.append('NA') 

# Extracting Views via Xpath
try:
    views_ele=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views_ele:
        Views.append(i.text)
except NoSuchElementExceptionhElementException:
    Views.append('NA')
except StaleElementReferenceException:
    Views.append('NA')

In [27]:
print(len(Rank),len(Name),len(Artist),len(Views),len(Upload_date))

30 30 30 30 30

In [28]:
max_length = max(len(Rank), len(Name), len(Artist), len(Views), len(Upload_date))

# Pad shorter lists with default values (e.g., None or empty string) to make them the same length
Rank         += [None] * (max_length - len(Rank))
Name         += [None] * (max_length - len(Name))
Artist       += [None] * (max_length - len(Artist))
Views        += [None] * (max_length - len(Views))
Upload_date  += [None] * (max_length - len(Upload_date))

In [29]:
# printing Dataframe for scrap data
wiki_video=pd.DataFrame({'Rank':Rank,'Video Name':Name,'Uploader':Artist,'Views (in Billons)':Views,'Upload Date':Upload_date})
print('\033[1m'+'Most Viewed Video on YouTube from Wikipedia :'+'\033[0m')
wiki_video

Most Viewed Video on YouTube from Wikipedia :

,Rank,Video Name,Uploader,Views (in Billons),Upload Date
0,1.,"""Baby Shark Dance""[6]",Pinkfong Baby Shark - Kids' Songs & Stories,13.36,"June 17, 2016"
1,2.,"""Despacito""[9]",Luis Fonsi,8.26,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[16]",LooLoo Kids - Nursery Rhymes and Children's Songs,6.80,"October 8, 2016"
3,4.,"""Bath Song""[17]",Cocomelon - Nursery Rhymes,6.41,"May 2, 2018"
4,5.,"""Shape of You""[18]",Ed Sheeran,6.08,"January 30, 2017"
5,6.,"""See You Again""[21]",Wiz Khalifa,6.03,"April 6, 2015"
6,7.,"""Wheels on the Bus""[26]",Cocomelon - Nursery Rhymes,5.56,"May 24, 2018"
7,8.,"""Phonics Song with Two Words""[27]",ChuChu TV Nursery Rhymes & Kids Songs,5.48,"March 6, 2014"
8,9.,"""Uptown Funk""[28]",Mark Ronson,5.03,"November 19, 2014"
9,10.,"""Learning Colors – Colorful Eggs on a Farm""[29]",Miroshka TV,4.97,"February 27, 2018"
10,11.,"""Gangnam Style""[30]",officialpsy,4.90,"July 15, 2012"
11,12.,"""Masha and the Bear – Recipe for Disaster""[35]",Get Movies,4.56,"January 31, 2012"
12,13.,"""Dame Tu Cosita""[36]",Ultra Records,4.44,"April 5, 2018"
13,14.,"""Axel F""[37]",Crazy Frog,4.06,"June 16, 2009"
14,15.,"""Sugar""[38]",Maroon 5,3.93,"January 14, 2015"
15,16.,"""Counting Stars""[39]",OneRepublic,3.87,"May 31, 2013"
16,17.,"""Roar""[40]",Katy Perry,3.87,"September 5, 2013"
17,18.,"""Baa Baa Black Sheep""[41]",Cocomelon - Nursery Rhymes,3.78,"June 25, 2018"
18,19.,"""Waka Waka (This Time for Africa)""[42]",Shakira,3.73,"June 4, 2010"
19,20.,"""Sorry""[43]",Justin Bieber,3.71,"October 22, 2015"
20,21.,"""Lakdi Ki Kathi""[44]",Jingle Toons,3.69,"June 14, 2018"
21,22.,"""Thinking Out Loud""[45]",Ed Sheeran,3.66,"October 7, 2014"
22,23.,"""Dark Horse""[46]",Katy Perry,3.59,"February 20, 2014"
23,24.,"""Humpty the train on a fruits ride""[47]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,3.55,"January 26, 2018"
24,25.,"""Perfect""[48]",Ed Sheeran,3.54,"November 9, 2017"
25,26.,"""Faded""[49]",Alan Walker,3.51,"December 3, 2015"
26,27.,"""Let Her Go""[50]",Passenger,3.51,"July 25, 2012"
27,28.,"""Girls Like You""[51]",Maroon 5,3.48,"May 31, 2018"
28,29.,"""Lean On""[52]",Major Lazer Official,3.46,"March 22, 2015"
29,30.,"""Bailando""[53]",Enrique Iglesias,3.45,"April 11, 2014"

Q2.
Scrape the details team India’s international fixtures from bcci.tv. 

Url = https://www.bcci.tv/.

You need to find following details:

A) Match title (I.e. 1 ODI) 
B) Series 
C) Place 
D) Date 
E) Time 
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [36]:
driver = webdriver.Chrome()

# Opening the flipkart.com pag Son the automated chome browser
driver.get('https://www.bcci.tv/')
time.sleep(2)
#maximize the window
driver.maximize_window()

In [37]:
# Opening fixtures webpage through browser
intrnl_fixtures=driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
try:
    intrnl_fixtures.click()
except ElementNotInteractableException:
    driver.get(fixtures.get_attribute('href'))

In [38]:
Title=[]
Series=[]
Place=[]
Date=[]
Time=[]

In [40]:
try:
    titles=driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
    for title in titles:
        Title.append(title.text)
except NoSuchElementException:
    Title.append('NA')
    
try:
    series_ele=driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
    for series in series_ele:
        Series.append(series.text)
except NoSuchElementException:
    Series.append('NA')
    
try:
    place_ele=driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')
    for place in place_ele:
        Place.append(place.text)
except NoSuchElementException:
    Place.append('NA')

try:
    date_ele=driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
    for date in date_ele:
        Date.append(date.text)
except NoSuchElementException:
    Date.append('NA')

try:
    time_ele=driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
    for time in time_ele:
        Time.append(time.text)
except NoSuchElementException:
    Time.append('NA')

In [41]:
print(len(Title),len(Series),len(Place),len(Date),len(Time))

8 8 8 8 8

In [42]:
# Dataframe for the same as per below
BCCI_Schedule=pd.DataFrame({'Match Title':Title,'Series Name':Series,'Place Name':Place,'Date':Date,'Time':Time})
BCCI_Schedule

,Match Title,Series Name,Place Name,Date,Time
0,Final -,ASIA CUP 2023,Colombo,17 SEP 2023,3:00 PM IST
1,1st T20I -,19TH ASIAN GAMES 2023,Hangzhou,21 SEP 2023,6:30 AM IST
2,1st ODI -,AUSTRALIA TOUR OF INDIA 2023-24,Mohali,22 SEP 2023,1:30 PM IST
3,2nd ODI -,AUSTRALIA TOUR OF INDIA 2023-24,Indore,24 SEP 2023,1:30 PM IST
4,3rd ODI -,AUSTRALIA TOUR OF INDIA 2023-24,Rajkot,27 SEP 2023,1:30 PM IST
5,1st ODI -,ICC MENS WORLD CUP 2023 WARM-UP MATCHES,Guwahati,30 SEP 2023,2:00 PM IST
6,1st T20I -,19TH ASIAN GAMES 2023,Hangzhou,3 OCT 2023,6:30 AM IST
7,2nd ODI -,ICC MENS WORLD CUP 2023 WARM-UP MATCHES,Thiruvananthapuram,3 OCT 2023,2:00 PM IST

Q3 .
Scrape the details of State-wise GDP of India from statisticstime.com. 

Url = http://statisticstimes.com/

You have to find following details:

A)Rank 
B) State 
C) GSDP(18-19)- at current prices 
D) GSDP(19-20)- at current prices 
E) Share(18-19) 
F) GDP($ billion) 

Note: - From statisticstimes home page you have to reach to economy page through code.

In [51]:
driver = webdriver.Chrome()

In [52]:
# Opening the flipkart.com pag Son the automated chome browser
driver.get('https://www.statisticstimes.com')

In [53]:
#maximize the window
driver.maximize_window()

In [59]:
india_dropdown=driver.find_element(By.XPATH,'//div[@class="dropdown"][2]/div/a[3]')

try:
    india_dropdown.click()
except ElementNotInteractableException:
    driver.get(india_dropdown.get_attribute('href'))
    
time.sleep(3)

In [62]:
gdp_india_states=driver.find_element(By.XPATH,'//ul[@style="list-style-type:none;margin-left:20px;"]/li[1]/a')
try:
    gdp_india_states.click()
except ElementNotInteractableException:
    gdp_india_states.get(india_dropdown.get_attribute('href'))
    
time.sleep(3)

In [63]:
rank=[]
state=[]
GSDP_18_19=[]
GSDP_19_20=[]
share=[]
GDP_bln=[]

In [64]:
try:
    rank_ele=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[1]')
    for i in rank_ele:
        rank.append(i.text)
except NoSuchElementException:
    rank.append('NA')

try:
    state_ele=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[2]')
    for i in state_ele:
        state.append(i.text)
except NoSuchElementException:
    state.append('NA')

try:
    gsdp_ele=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[3]')
    for i in gsdp_ele:
        GSDP_19_20.append(i.text)
except NoSuchElementException:
    GSDP_18_19.append('NA')
    
try:
    gsdp_ele=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[4]')
    for i in gsdp_ele:
        GSDP_18_19.append(i.text)
except NoSuchElementException:
    GSDP_19_20.append('NA')


try:
    share_ele=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[5]')
    for i in share_ele:
        share.append(i.text)
except NoSuchElementException:
    share.append('NA')    
    
    
try:
    gdp_ele=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[6]')
    for i in gdp_ele:
        GDP_bln.append(i.text)
except NoSuchElementException:
    GDP_bln.append('NA')

In [65]:
print(len(rank),len(state),len(GSDP_18_19),len(GSDP_19_20),len(share),len(GDP_bln))

33 33 33 33 33 33

In [69]:
# Dataframe for the above data
Statewise_GDP=pd.DataFrame({'Rank':rank,'State':state,'GSDP 19-20':GSDP_19_20,'GSDP 18-19':GSDP_18_19,
                            'Share':share,'GDP (in Billions)':GDP_bln})
print('\033[1m'+'State-wise GDP of India :'+'\033[0m')
Statewise_GDP

State-wise GDP of India :

,Rank,State,GSDP 19-20,GSDP 18-19,Share,GDP (in Billions)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

Q4.
Scrape the details of trending repositories on Github.com. 

Url = https://github.com/

You have to find the following details: 
A) Repository title 
B) Repository description 
C) Contributors count
D) Language used 

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [78]:
driver = webdriver.Chrome()

# Opening the github website
driver.get('https://www.github.com')


#maximize the window
driver.maximize_window()

In [79]:
#Clicking Open Source
source =driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
source.click()

#clicking Trending
trending=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a')
trending.click()

In [80]:
title=[]
desc=[]
count=[]
langu=[]

In [82]:
try:
    title_ele=driver.find_elements(By.XPATH,'//h2[@class="h3 lh-condensed"]')
    for i in title_ele:
        title.append(i.text)
except NoSuchElementException:
    title.append('NA')

try:
    desc_ele=driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
    for i in desc_ele:
        desc.append(i.text)
except NoSuchElementException:
    desc.append('NA')

try:
    count_ele=driver.find_elements(By.XPATH,'//div[@class="f6 color-fg-muted mt-2"]/a')
    for i in count_ele:
        count.append(i.text)
except NoSuchElementException:
    count.append('NA')

try:
    langu_ele=driver.find_elements(By.XPATH,'//span[@class="d-inline-block ml-0 mr-3"]')
    for i in langu_ele:
        langu.append(i.text)
except NoSuchElementException:
    langu.append('NA')

In [83]:
print(len(title),len(desc),len(count),len(langu))

50 25 50 24

In [84]:
max_length = max(len(title), len(desc), len(count),len(langu))

# Pad shorter lists with default values (e.g., None or empty string) to make them the same length
title    += [None] * (max_length - len(title))
desc     += [None] * (max_length - len(desc))
count    += [None] * (max_length - len(count))
langu    += [None] * (max_length - len(langu))

In [87]:
# Dataframe for the above data
trending_rep=pd.DataFrame({'Repository Title':title,'Repository Description':desc,'Count':count,'Language':langu})

trending_rep

,Repository Title,Repository Description,Count,Language
0,godotengine /,Godot Engine – Multi-platform 2D and 3D game e...,"68,652",C++
1,yoheinakajima /,Converts text input or URL into knowledge grap...,"14,012",Python
2,apache /,Apache IoTDB,"1,539",Java
3,zhile-io /,"潘多拉，一个让你呼吸顺畅的ChatGPT。Pandora, a ChatGPT client...",150,Python
4,isocpp /,The C++ Core Guidelines are a set of tried-and...,"3,900",Python
5,testerSunshine /,12306智能刷票，订票,925,Python
6,tldraw /,a very good whiteboard,831,TypeScript
7,jedisct1 /,"A modern, portable, easy to use crypto library.",136,C
8,grpc /,"The C based gRPC (C++, Python, Ruby, Objective...","38,947",C++
9,ray-project /,A comprehensive guide to building RAG-based LL...,"5,268",Jupyter Notebook
10,microsoft /,🤖 💼 Azure Chat Solution Accelerator powered by...,"31,501",TypeScript
11,d2l-ai /,《动手学深度学习》：面向中文读者、能运行、可讨论。中英文版被70多个国家的500多所大学用于教学。,"9,473",Python
12,godotengine /,Demonstration and Template Projects,"19,357",GDScript
13,ddbourgin /,"Machine learning, in numpy","1,098",Python
14,keras-team /,Deep Learning for humans,"11,414",Python
15,stevearc /,Lightweight yet powerful formatter plugin for ...,"1,724",Lua
16,pjialin /,🚂 12306 购票助手，支持集群，多账号，多任务购票以及 Web 页面管理,"38,979",Python
17,gnobitab /,⚡ InstaFlow! One-Step Stable Diffusion with Re...,"10,466",C++
18,google /,GoogleTest - Google Testing and Mocking Framework,483,Go
19,pulumi /,Pulumi - Infrastructure as Code in any program...,47,Python
20,facebookresearch /,Implementation of Nougat Neural Optical Unders...,320,JavaScript
21,OpenBMB /,🤖 AgentVerse 🪐 provides a flexible framework t...,101,Rust
22,massalabs /,The Decentralized and Scaled Blockchain,"48,126",Python
23,n0a /,Get IP address on other side audio call in Tel...,"9,583",Vim Script
24,vim /,The official Vim repository,"3,746",None
25,godotengine / godot,None,"1,326",None
26,yoheinakajima / instagraph,None,"13,177",None
27,apache / iotdb,None,"3,446",None
28,zhile-io / pandora,None,"59,279",None
29,isocpp / CppCoreGuidelines,None,"19,404",None
30,testerSunshine / 12306,None,278,None
31,tldraw / tldraw,None,12,None
32,jedisct1 / libsodium,None,"12,060",None
33,grpc / grpc,None,"3,133",None
34,ray-project / llm-applications,None,319,None
35,microsoft / azurechat,None,6,None
36,d2l-ai / d2l-zh,None,"30,789",None
37,godotengine / godot-demo-projects,None,"9,813",None
38,ddbourgin / numpy-ml,None,"17,459",None
39,keras-team / keras,None,966,None
40,stevearc / conform.nvim,None,"4,610",None
41,pjialin / py12306,None,278,None
42,gnobitab / InstaFlow,None,"1,534",None
43,google / googletest,None,141,None
44,pulumi / pulumi,None,"4,327",None
45,facebookresearch / nougat,None,626,None
46,OpenBMB / AgentVerse,None,594,None
47,massalabs / massa,None,80,None
48,n0a / telegram-get-remote-ip,None,"32,722",None
49,vim / vim,None,"4,984",None

Q5.
Scrape the details of top 100 songs on billiboard.com. 

Url = https:/www.billboard.com/

You have to find the following details: 

A) Song name 
B) Artist name 
C) Last week rank 
D) Peak rank 
E) Weeks on board 

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [5]:
driver = webdriver.Chrome()

# Opening the flipkart.com pag Son the automated chome browser
driver.get('https://www.billboard.com/')
time.sleep(3)
#maximize the window
driver.maximize_window()

In [6]:
#Clicking on the menu
menu=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[1]/div[1]/button')
menu.click()

In [7]:
#Clicking top 100
top = driver.find_element(By.XPATH,'/html/body/div[3]/div[9]/div/div/div/ul/li[1]/ul/li[2]/a')
top.click()

In [8]:
#Extracting Required Data
data=[i.text.split('\n') for i in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]')]

driver.close()

#Creating DataFrame:
columns = ['Song name', 'Artist Name', 'Last Weak Rank', 'Peak Rank', 'Weeks on Chart']

Top100 = pd.DataFrame(data, columns=columns)
Top100

,Song name,Artist Name,Last Weak Rank,Peak Rank,Weeks on Chart
0,Vampire,Olivia Rodrigo,9,1,11
1,Paint The Town Red,Doja Cat,1,1,6
2,I Remember Everything,Zach Bryan Featuring Kacey Musgraves,2,1,3
3,Fast Car,Luke Combs,3,2,25
4,Cruel Summer,Taylor Swift,4,3,19
...,...,...,...,...,...
95,Lagunas,Peso Pluma & Jasiel Nunez,-,77,9
96,Sittin' On Top Of The World,Burna Boy,86,80,3
97,Rubicon,Peso Pluma,95,63,11
98,TQM,Fuerza Regida,89,34,17
99,Amargura,Karol G,91,85,5

Q6. 
Scrape the details of Highest selling novels. 

compare 

A) Book name 
B) Author name 
C) Volumes sold 
D) Publisher 
E) Genre

Note : Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greyYou

In [11]:
driver = webdriver.Chrome()

# Opening the flipkart.com pag Son the automated chome browser
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")
time.sleep(3)
#maximize the window
driver.maximize_window()

In [12]:
#Extracting Book Name
book =[i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]')]

#Extracting Author Name
author = [i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]')]

#Extracting Volumes sold
vol = [i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]')]

#Extracting Publisher
pub = [i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]')]

#Extracting Genre
gen = [i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]')]

driver.close()
print(len(book),len(author),len(vol),len(pub), len(gen))

# Convertingin Dataframe:
Highest_selling_novels=pd.DataFrame({
    "Book Name": book,
    "Author Name":author,
    "Volumes sold":vol,
    "Publisher": pub,
    "Genre" : gen
})

Highest_selling_novels

100 100 100 100 100

,Book Name,Author Name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

Q7.
Scrape the details most watched tv series of all time from imdb.com.

Url = https://www.imdb.com/list/ls095964455/ 

You have to find the following details:

Name
Year span
Genre
Run time
Ratings
Votes

In [13]:
driver = webdriver.Chrome()

# Opening the flipkart.com pag Son the automated chome browser
driver.get("https://www.imdb.com/list/ls095964455/")
time.sleep(3)
#maximize the window
driver.maximize_window()

In [14]:
#Extracting Name:
name =[i.text for i in driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a')]

# Extracting Year Span
year = [i.text for i in driver.find_elements(By.XPATH,'//span[@class="lister-item-year text-muted unbold"]')]

#Extracting Genre 
genre = [i.text for i in driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[5]')]

#Extracting Run time
time = [i.text for i in driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[3]')]

#Extracting Rating
rating = [i.text for i in driver.find_elements(By.XPATH,'//div[@class="ipl-rating-widget"]/div/span[2]')]

#Extracting Votes
voting = [i.text for i in driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"][3]/span[2]')]

driver.close()
print(len(name), len(year), len(genre), len(time), len(rating),len(voting))

#Creating DataFrame
most_watched_tv_series=pd.DataFrame({
    "Name": name,
    "Year span":year,
    "Genre":genre,
    "Run time":time,
    "Ratings":rating,
    "Votes": voting
})
most_watched_tv_series

100 100 100 100 100 100

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,205,121"
1,Stranger Things,(2016–2025),"Drama, Fantasy, Horror",51 min,8.7,"1,276,463"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,046,267"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"307,502"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"266,580"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.5,"52,750"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"64,810"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"211,109"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7,"43,923"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"266,198"

Q 8.
Details of Datasets from UCI machine learning repositories.

Url = https://archive.ics.uci.edu/ 

You have to find the following details:

Dataset name
Data type
Task
Attribute type
No of instances
No of attribute
Year

In [38]:
driver = webdriver.Chrome()

# Opening the flipkart.com pag Son the automated chome browser
driver.get("https://archive.ics.uci.edu/")

#maximize the window
driver.maximize_window()

In [39]:
#clicking all dataset
dataset=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/header/nav/ul/li[1]/a')
dataset.click()

In [40]:
name=[]
datatype=[]
task=[]
instances=[]
no_attribute=[]
attributetype=[]
year=[]

In [30]:
try:
    name_ele=driver.find_elements(By.XPATH,'//h2[@class="truncate text-primary"]')
    for i in name_ele:
        name.append(i.text)
except NoSuchElementException:
    name.append('NA')

try:
    task_ele=driver.find_elements(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div[1]/div/div[2]/div/div[1]/span')
    for i in task_ele:
        task.append(i.text)
except NoSuchElementException:
    task.append('NA')

try:
    instances_ele=driver.find_elements(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div[1]/div/div[2]/div/div[3]/span')
    for i in instances_ele:
        instances.append(i.text)
except NoSuchElementException:
    instances.append('NA')

try:
    no_attribute_ele=driver.find_elements(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div[1]/div/div[2]/div/div[4]/span')
    for i in no_attribute_ele:
        no_attribute.append(i.text)
except NoSuchElementException:
    no_attribute.append('NA')

In [ ]:
## could not found datatype, attribute type

In [31]:
print(len(name),len(task),len(instances),len(no_attribute))

30 3 3 3

In [34]:
instances

['150 Instances', '150 Instances', '150 Instances']